name: "Bitvavo Trading Bot"
description: "AI-gestuurde crypto trading bot met web dashboard"
version: "1.16.1"
slug: "bitvavo_bot"
init: false
arch:
  - aarch64
  - armv7
  - armhf
  - amd64
ingress: true
ingress_port: 5001
map:
  - config:rw
options: {}
schema: {}
